python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=2 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=4 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=8 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=16 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=32 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=64 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=128 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=256 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=512 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=1024 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=2048 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=4096 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=8192 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=16384 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=32768 --log_wandb=True --gpu_id=0
python run_recbole.py --dataset=gowalla-merged --model=BPR --embedding_size=65536 --log_wandb=True --gpu_id=0

python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=2 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=4 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=8 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=16 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=32 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=64 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=128 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=256 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=512 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=1024 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=2048 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=4096 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=8192 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=16384 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=32768 --log_wandb=True --gpu_id=1
python run_recbole.py --dataset=gowalla-merged --model=LightGCN --embedding_size=65536 --log_wandb=True --gpu_id=1

python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=2 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=4 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=8 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=16 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=32 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=64 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=128 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=256 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=512 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=1024 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=2048 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=4096 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=8192 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=16384 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=32768 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=SGL --embedding_size=65536 --log_wandb=True --gpu_id=7

python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=2 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=4 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=8 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=16 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=32 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=64 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=128 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=256 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=512 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=1024 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=2048 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=4096 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=8192 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=16384 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=32768 --log_wandb=True --gpu_id=7
python run_recbole.py --dataset=gowalla-merged --model=NeuMF --embedding_size=65536 --log_wandb=True --gpu_id=7